export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};

export const actionTypeBuy = {
  ADD_PRODUCT: "ADD_PRODUCT",
  INCRESR_QTY: "INCRESR_QTY",
  INCRESE_QTY_BY_INPUT: "INCRESE_QTY_BY_INPUT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};

export const actionToSign = {
  LGO_IN: "LGO_IN",
};
